name: Build pre-release
# Don't enable CI on push, just on PR. If you
# are working on the main repo and want to trigger
# a CI build submit a draft PR.
on: 
  push:
    branches:
    - master
      mmosca-update-github-actions
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          id: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build
      - name: Setup environment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          # This is the hash of the commit for the PR
          # when the action is triggered by PR, empty otherwise
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          # This is the hash of the commit when triggered by push
          # but the hash of refs/pull/<n>/merge, which is different
          # from the hash of the latest commit in the PR, that's
          # why we try github.event.pull_request.head.sha first
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=dev-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep project CMakeLists.txt|awk -F VERSION '{ gsub(/^[ \t]+|[ \t\)]+$/, "", $2); print $2 }')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=inav-${VERSION}-${BUILD_SUFFIX}" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: downloads
          key: ${{ runner.os }}-downloads-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('**/cmake/*')}}
      - name: Build targets (${{ matrix.id }})
        run: mkdir -p build && cd build && cmake -DWARNINGS_AS_ERRORS=ON -DCI_JOB_INDEX=${{ matrix.id }} -DCI_JOB_COUNT=${{ strategy.job-total }} -DBUILD_SUFFIX=${{ env.BUILD_SUFFIX }} -G Ninja .. && ninja ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}.${{ matrix.id }}
          path: ./build/*.hex

  build-SITL-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build
      - name: Setup environment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          # This is the hash of the commit for the PR
          # when the action is triggered by PR, empty otherwise
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          # This is the hash of the commit when triggered by push
          # but the hash of refs/pull/<n>/merge, which is different
          # from the hash of the latest commit in the PR, that's
          # why we try github.event.pull_request.head.sha first
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=dev-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep project CMakeLists.txt|awk -F VERSION '{ gsub(/[ \t\)]+/, "", $2); print $2 }')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=inav-${VERSION}-${BUILD_SUFFIX}" >> $GITHUB_ENV
      - name: Build SITL
        run: mkdir -p build_SITL && cd build_SITL && cmake -DSITL=ON -DWARNINGS_AS_ERRORS=ON -G Ninja .. && ninja
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitl-${{ env.BUILD_NAME }}-Linux
          path: ./build_SITL/*_SITL

  build-SITL-Mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install cmake ninja ruby

      - name: Setup environment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          # This is the hash of the commit for the PR
          # when the action is triggered by PR, empty otherwise
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          # This is the hash of the commit when triggered by push
          # but the hash of refs/pull/<n>/merge, which is different
          # from the hash of the latest commit in the PR, that's
          # why we try github.event.pull_request.head.sha first
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=dev-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep project CMakeLists.txt|awk -F VERSION '{ gsub(/[ \t\)]+/, "", $2); print $2 }')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=inav-${VERSION}-${BUILD_SUFFIX}" >> $GITHUB_ENV
      - name: Build SITL
        run: |
          mkdir -p build_SITL && cd build_SITL
          cmake -DSITL=ON -DWARNINGS_AS_ERRORS=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -G Ninja ..
          ninja

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitl-${{ env.BUILD_NAME }}-MacOS
          path: ./build_SITL/*_SITL

  build-SITL-Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe -o igncr '{0}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake ruby ninja gcc-g++
      - name: Setup environment
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          # This is the hash of the commit for the PR
          # when the action is triggered by PR, empty otherwise
          COMMIT_ID=${{ github.event.pull_request.head.sha }}
          # This is the hash of the commit when triggered by push
          # but the hash of refs/pull/<n>/merge, which is different
          # from the hash of the latest commit in the PR, that's
          # why we try github.event.pull_request.head.sha first
          COMMIT_ID=${COMMIT_ID:-${{ github.sha }}}
          BUILD_SUFFIX=dev-$(date '+%Y%m%d')-$(git rev-parse --short ${COMMIT_ID})
          VERSION=$(grep project CMakeLists.txt|awk -F VERSION '{ gsub(/[ \t\)]+/, "", $2); print $2 }')
          echo "BUILD_SUFFIX=${BUILD_SUFFIX}" >> $GITHUB_ENV
          echo "BUILD_NAME=inav-${VERSION}-${BUILD_SUFFIX}" >> $GITHUB_ENV
      - name: Build SITL
        run: mkdir -p build_SITL && cd build_SITL && cmake -DSITL=ON -DWARNINGS_AS_ERRORS=ON -G Ninja .. && ninja
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitl-${{ env.BUILD_NAME }}-WIN
          path: ./build_SITL/*.exe


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install ninja-build
      - name: Run Tests
        run: mkdir -p build && cd build && cmake -DTOOLCHAIN=none -G Ninja .. && ninja check

  release:
    needs: [build, build-SITL-Linux, build-SITL-Mac, build-SITL-Windows, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "today=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: hexes
          pattern: inav-*
          merge-multiple: true
      - name: download sitl linux
        uses: actions/download-artifact@v4
        with:
          path: resources/sitl/linux
          pattern: sitl-*-Linux
          merge-multiple: true
      - name: download sitl windows
        uses: actions/download-artifact@v4
        with:
          path: resources/sitl/windows
          pattern: sitl-*-WIN
          merge-multiple: true
      - name: download sitl mac
        uses: actions/download-artifact@v4
        with:
          path: resources/sitl/macos
          pattern: sitl-*-MacOS
          merge-multiple: true
      - name: Consolidate sitl files
        run: |
          zip -r -9 sitl-resources.zip resources/
      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: inav-dev-release-${{ steps.date.outputs.today }}-${{ github.run_id }}-${{ github.sha}}
          tag_name: v${{ steps.date.outputs.today }}.${{ github.run_number }}
          # To create release on a different repo, we need a token setup
          #token: ${{ secrets.GITHUB_TOKEN }}
          repository: iNavFlight/inav
          prerelease: true
          draft: true
          generate_release_notes: true
          make_latest: false
          files: |
            hexes/*.hex
            sitl-resources.zip

